Updated benchmark to TSP 3.3 and TSC 3.1
IronCoreLabs/tenant-security-client-java pull request #67
Opened 2021-07-06 18:38 UTC by clintfred

2021-07-06 19:19 UTC, giarc3 approved these changes

2021-07-07 19:22 UTC, giarc3 requested changes

2021-07-07 19:22 UTC, giarc3 commented on benchmarks/README.md
> +mvn clean insteall
```suggestion
mvn clean install
```

2021-07-08 15:22 UTC, BobWall23 approved these changes

2021-07-08 20:24 UTC, coltfred approved these changes

2021-07-08 21:35 UTC, giarc3 approved these changes

2021-07-08 21:36 UTC, merged